# Generated by Django 5.0.2 on 2024-03-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_transaction_sale_assistant_customer_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='House_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
