# Generated by Django 5.0.2 on 2024-03-08 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_customer_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='transaction_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.transaction'),
        ),
    ]
